spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/scdbase"
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 10000
#      validation-timeout: 10000
#      idle-timeout: 10000
#      leak-detection-threshold: 10000
#      max-lifetime: 3600000
#      max-pool-size: 3
#      min-idle: 1000
#      is-auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.xml
  jackson:
    default-property-inclusion: non_absent
    serialization:
      write-dates-as-timestamps: false
  mvc:
    format:
      date: "yyyy-MM-dd HH:mm:ss"


#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          public-key-location: 'file:config/jwk-public.pem'


server.port: 8081
#server:
#  servlet:
#    contextPath: /core



logging:
  file:
    name: logs/serverapp.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
      file-name-pattern: logs/serverapp.%d{yyyy-MM-dd}.%i.log

  #request parameters date formatting

